/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace KoiCert {
  export type KoiDataStruct = {
    id: string;
    variety: string;
    breeder: string;
    gender: string;
    age: string;
    size: BigNumberish;
    condition: string;
    photoUrl: string;
    certUrls: string[];
    contestUrls: string[];
    timestamp: BigNumberish;
    issuer: AddressLike;
    currentOwner: AddressLike;
    fatherId: string;
    motherId: string;
  };

  export type KoiDataStructOutput = [
    id: string,
    variety: string,
    breeder: string,
    gender: string,
    age: string,
    size: bigint,
    condition: string,
    photoUrl: string,
    certUrls: string[],
    contestUrls: string[],
    timestamp: bigint,
    issuer: string,
    currentOwner: string,
    fatherId: string,
    motherId: string
  ] & {
    id: string;
    variety: string;
    breeder: string;
    gender: string;
    age: string;
    size: bigint;
    condition: string;
    photoUrl: string;
    certUrls: string[];
    contestUrls: string[];
    timestamp: bigint;
    issuer: string;
    currentOwner: string;
    fatherId: string;
    motherId: string;
  };

  export type HistoryStruct = {
    owner: AddressLike;
    ownerName: string;
    timestamp: BigNumberish;
    note: string;
    photoUrl: string;
    size: BigNumberish;
    age: string;
  };

  export type HistoryStructOutput = [
    owner: string,
    ownerName: string,
    timestamp: bigint,
    note: string,
    photoUrl: string,
    size: bigint,
    age: string
  ] & {
    owner: string;
    ownerName: string;
    timestamp: bigint;
    note: string;
    photoUrl: string;
    size: bigint;
    age: string;
  };
}

export interface KoiCertInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MINTER_ROLE"
      | "UPGRADER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "getKoi"
      | "getKoiHistory"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "koiHistories"
      | "koiRegistry"
      | "mintCertificate"
      | "proxiableUUID"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "transferOwnership"
      | "updateKoiStats"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "KoiMinted"
      | "KoiUpdated"
      | "OwnershipTransferred"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getKoi", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getKoiHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "koiHistories",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "koiRegistry", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mintCertificate",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [
      string,
      AddressLike,
      string,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateKoiStats",
    values: [
      string,
      BigNumberish,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKoi", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getKoiHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "koiHistories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "koiRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKoiStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KoiMintedEvent {
  export type InputTuple = [id: string, owner: AddressLike];
  export type OutputTuple = [id: string, owner: string];
  export interface OutputObject {
    id: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KoiUpdatedEvent {
  export type InputTuple = [
    id: string,
    newSize: BigNumberish,
    newNote: string,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    newSize: bigint,
    newNote: string,
    updatedBy: string
  ];
  export interface OutputObject {
    id: string;
    newSize: bigint;
    newNote: string;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [id: string, from: AddressLike, to: AddressLike];
  export type OutputTuple = [id: string, from: string, to: string];
  export interface OutputObject {
    id: string;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KoiCert extends BaseContract {
  connect(runner?: ContractRunner | null): KoiCert;
  waitForDeployment(): Promise<this>;

  interface: KoiCertInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  getKoi: TypedContractMethod<
    [_id: string],
    [KoiCert.KoiDataStructOutput],
    "view"
  >;

  getKoiHistory: TypedContractMethod<
    [_id: string],
    [KoiCert.HistoryStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [defaultAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  koiHistories: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, string] & {
        owner: string;
        ownerName: string;
        timestamp: bigint;
        note: string;
        photoUrl: string;
        size: bigint;
        age: string;
      }
    ],
    "view"
  >;

  koiRegistry: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string
      ] & {
        id: string;
        variety: string;
        breeder: string;
        gender: string;
        age: string;
        size: bigint;
        condition: string;
        photoUrl: string;
        timestamp: bigint;
        issuer: string;
        currentOwner: string;
        fatherId: string;
        motherId: string;
      }
    ],
    "view"
  >;

  mintCertificate: TypedContractMethod<
    [
      _id: string,
      _variety: string,
      _breeder: string,
      _gender: string,
      _age: string,
      _size: BigNumberish,
      _condition: string,
      _photoUrl: string,
      _certUrl: string,
      _contestUrl: string,
      _fatherId: string,
      _motherId: string,
      _note: string
    ],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [
      _id: string,
      _newOwner: AddressLike,
      _newOwnerName: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _note: string
    ],
    [void],
    "nonpayable"
  >;

  updateKoiStats: TypedContractMethod<
    [
      _id: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _newCertUrl: string,
      _newContestUrl: string,
      _updateNote: string
    ],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getKoi"
  ): TypedContractMethod<[_id: string], [KoiCert.KoiDataStructOutput], "view">;
  getFunction(
    nameOrSignature: "getKoiHistory"
  ): TypedContractMethod<
    [_id: string],
    [KoiCert.HistoryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[defaultAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "koiHistories"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, string] & {
        owner: string;
        ownerName: string;
        timestamp: bigint;
        note: string;
        photoUrl: string;
        size: bigint;
        age: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "koiRegistry"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string
      ] & {
        id: string;
        variety: string;
        breeder: string;
        gender: string;
        age: string;
        size: bigint;
        condition: string;
        photoUrl: string;
        timestamp: bigint;
        issuer: string;
        currentOwner: string;
        fatherId: string;
        motherId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCertificate"
  ): TypedContractMethod<
    [
      _id: string,
      _variety: string,
      _breeder: string,
      _gender: string,
      _age: string,
      _size: BigNumberish,
      _condition: string,
      _photoUrl: string,
      _certUrl: string,
      _contestUrl: string,
      _fatherId: string,
      _motherId: string,
      _note: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [
      _id: string,
      _newOwner: AddressLike,
      _newOwnerName: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _note: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateKoiStats"
  ): TypedContractMethod<
    [
      _id: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _newCertUrl: string,
      _newContestUrl: string,
      _updateNote: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "KoiMinted"
  ): TypedContractEvent<
    KoiMintedEvent.InputTuple,
    KoiMintedEvent.OutputTuple,
    KoiMintedEvent.OutputObject
  >;
  getEvent(
    key: "KoiUpdated"
  ): TypedContractEvent<
    KoiUpdatedEvent.InputTuple,
    KoiUpdatedEvent.OutputTuple,
    KoiUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "KoiMinted(string,address)": TypedContractEvent<
      KoiMintedEvent.InputTuple,
      KoiMintedEvent.OutputTuple,
      KoiMintedEvent.OutputObject
    >;
    KoiMinted: TypedContractEvent<
      KoiMintedEvent.InputTuple,
      KoiMintedEvent.OutputTuple,
      KoiMintedEvent.OutputObject
    >;

    "KoiUpdated(string,uint256,string,address)": TypedContractEvent<
      KoiUpdatedEvent.InputTuple,
      KoiUpdatedEvent.OutputTuple,
      KoiUpdatedEvent.OutputObject
    >;
    KoiUpdated: TypedContractEvent<
      KoiUpdatedEvent.InputTuple,
      KoiUpdatedEvent.OutputTuple,
      KoiUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(string,address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
